[package]
name = "chmopass"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.10.2"
config = "0.15.11"
dotenv = "0.15.0"
futures-util = "0.3.31"
jsonwebtoken = "9.3.1"
reqwest = { version = "0.12.12", features = ["json", "rustls-tls"], default-features = false }
serde = "1.0.219"
