debug = true
server_port = 8080

expiration_seconds = 3600
private_pem_filename = "private.pem"
authorized_github_ids =[36817478]

[credentials]
client_id = "chmopass"
client_secret = "chmopass"

[auth]
pem_file = "public.pem"
