name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  release:
    types: [published]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: actions/cache@v3.4.3
      with:
        path: '**/target'
        key: ${{ runner.os }}-${{ hashFiles('**/Cargo.lock') }}
    - name: Build chmopass
      run: cargo build --release
    - name: Upload chmopass artifact
      uses: actions/upload-artifact@v4.6.1
      if: github.event_name == 'release'
      with: 
        path: chmopass/target/release/chmopass
        name: chmopass-${{github.event.release.tag_name}}
